@startuml

hide empty members
hide circle

class Agenda
class Task
class Project
class Team
class Resource
class User
class Inventory

Agenda - Task
Project "1" -- "*" Task
Task "1" -- "*" Resource
Team "1" -- "*" User : < belong to
Team "1" -- "1" User : < lead

Task - User
User "1" - "*" Role

Inventory - Resource
@enduml
